### PR TITLE
Fix: getLogFileList

### PR DESCRIPTION
**Pull request by komicho**
I was having trouble displaying all the records if the file was not named laravel.log

### CODE REVIEW

**Comment by stevebauman** [comment]
Ah great catch, thanks @komicho!

**Comment by komicho** [comment]
You can merge my request because I want to use this modification .. Inside one of my projects
https://github.com/zaoub/laravel-logger.
thanks.
@stevebauman

**Comment by stevebauman** [comment]
Of course, I’ll merge and fix the tests for new Laravel versions and then create a new release.

**Comment by komicho** [comment]
Thanks

**Pull request merged**
